# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfb43e75abca05b4f3df9af9d80805526d9e6f18c04278a2c62696cc8d3bf088d69f5455f9d3cc17460c15092a309d34dc85bbb9950993d6c6265473a1f65814

test:
  secret_key_base: 62d07afec8fe05d209622280c13f49fe0337b752bf679f6f9a140f7e8708425dc1f38cf9a8fcf424382a88027b423b452a57b48e044f85a73e32659d60ee8b8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
